### ISSUE TITLE
ruby 2.2.2 installation fails on Ubuntu 15.04

### ISSUE THREAD

**Issue by d2s** [postmodern/ruby-install#223] opened 2015-05-15 09:52 UTC
Install fails when running:
```
 $ ruby-install ruby 2.2.2
```

_(I had already installed previous ruby-2.1.3 version with `ruby-install ruby` and that did work as expected.)_

### Essential parts

```
make[2]: Entering directory '/home/d2s/src/ruby-2.2.2'
linking ruby
make[2]: Leaving directory '/home/d2s/src/ruby-2.2.2'
make[1]: Leaving directory '/home/d2s/src/ruby-2.2.2'
Generating RDoc documentation
Parsing sources...
100% [966/966]  vsnprintf.c                                                

Generating RI format into /home/d2s/src/ruby-2.2.2/.ext/rdoc...
Killed
uncommon.mk:427: recipe for target 'rdoc' failed
make: *** [rdoc] Error 137
!!! Compiling ruby 2.2.2 failed!
```

Full terminal log can be seen at [Gist](https://gist.github.com/d2s/50b85708dfc99a2c06e5).

#### Kernel version:
```
$ uname -a
Linux d2s-VirtualBox 3.19.0-16-generic #16-Ubuntu SMP Thu Apr 30 16:09:58 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

#### VirtualBox

Running Ubuntu inside VirtualBox 4.3.28 r100309

**Comment by postmodern** [comment] 2015-05-27 21:32
Can you reproduce this manually to prove it's not caused by ruby-install?

**Comment by chalmagean** [comment] 2015-07-13 14:06
+1 this is weird, it worked fine on a VM but failed on my VPS

**Comment by Extrapolator214** [comment] 2015-08-09 10:12
+1. It works fine for me on local Ubuntu 15.04, but fails on DigitalOcean VPS.
Workaround: RUBY_CONFIGURE_OPTS=--disable-install-doc (as suggested here: https://github.com/sstephenson/ruby-build/issues/729 )
```
deploy@domain:~$ rbenv install 2.2.2
Downloading ruby-2.2.2.tar.gz...
-> https://dqw8nmjcqpjn7.cloudfront.net/5ffc0f317e429e6b29d4a98ac521c3ce65481bfd22a8cf845fa02a7b113d9b44
Installing ruby-2.2.2...

BUILD FAILED (Ubuntu 15.04 using ruby-build 20150803)

Inspect or clean up the working tree at /tmp/ruby-build.20150809054729.2714
Results logged to /tmp/ruby-build.20150809054729.2714.log

Last 10 log lines:
 99% [963/967]  vm_exec.c
 99% [964/967]  vm_insnhelper.c
 99% [965/967]  vm_method.c
 99% [966/967]  vm_trace.c
100% [967/967]  vsnprintf.c

Generating RI format into /tmp/ruby-build.20150809054729.2714/ruby-2.2.2/.ext/rdoc...
Killed
uncommon.mk:427: recipe for target 'rdoc' failed
make: *** [rdoc] Error 137

deploy@domain:~$ RUBY_CONFIGURE_OPTS=--disable-install-doc rbenv install 2.2.2
Downloading ruby-2.2.2.tar.gz...
-> https://dqw8nmjcqpjn7.cloudfront.net/5ffc0f317e429e6b29d4a98ac521c3ce65481bfd22a8cf845fa02a7b113d9b44
Installing ruby-2.2.2...
Installed ruby-2.2.2 to /home/deploy/.rbenv/versions/2.2.2

deploy@domain:~$ 
```

**Comment by postmodern** [comment] 2015-12-28 00:51
Also found the same upstream bug report: https://bugs.ruby-lang.org/issues/11494

@hsbt is this is a known or fixed bug? Are people still running into this with 2.2.3 or 2.2.4?

**Comment by hsbt** [comment] 2015-12-28 23:55
fmm, It's not ruby bug. It seems to happen OOM killer at tiny VM to me.

**Comment by postmodern** [comment] 2015-12-29 02:18
That would explain why it fails on some Ubuntu VMs but not others. Going to close this for now.

**Closed by postmodern** 2015-12-29 02:18 UTC

**Comment by postmodern** [comment] 2015-12-29 02:19
As a workaround, users can specify: `ruby-install ruby 2.2.2 -- --disable-install-doc`

**Comment by bluebaroncanada** [comment] 2016-09-13 22:24
This issue still exists.

**Comment by imranashraf** [comment] 2017-10-31 14:59
This issue still appears when installing ruby 2.2.3 on Ubuntu 17.10. However the following solves the problem:

`RUBY_CONFIGURE_OPTS=--disable-install-doc rbenv install 2.2.3`

**Comment by trusche** [comment] 2017-11-29 15:25
For anyone else coming across this, the issue seems to be the install process running out of memory on smaller VMs with <= 1G RAM. It's not Ubuntu-specific AFAIK. Adding some swap space did the trick for me. See for example https://www.digitalocean.com/community/tutorials/how-to-add-swap-space-on-ubuntu-16-04.

**Comment by TJC** [comment] 2017-12-07 05:49
I've been hitting this exact problem installing ruby 2.2.3, but this is on a machine with 32G of ram, and 23G of that free during the install -- so it's not memory starvation.

```
Generating RDoc documentation             
Parsing sources...   
100% [967/967]  vsnprintf.c                                                          

Generating RI format into /home/tjc/src/ruby-2.2.3/.ext/rdoc...                      
Marshal.dump reentered at marshal_dump    
/home/tjc/src/ruby-2.2.3/lib/rdoc/store.rb:865:in `dump'                             
        /home/tjc/src/ruby-2.2.3/lib/rdoc/store.rb:865:in `save_class'               
        /home/tjc/src/ruby-2.2.3/lib/rdoc/store.rb:749:in `block in save'            
        /home/tjc/src/ruby-2.2.3/lib/rdoc/store.rb:748:in `each'                     
        /home/tjc/src/ruby-2.2.3/lib/rdoc/store.rb:748:in `save'                     
        /home/tjc/src/ruby-2.2.3/lib/rdoc/generator/ri.rb:26:in `generate'           
        /home/tjc/src/ruby-2.2.3/lib/rdoc/rdoc.rb:530:in `block in generate'         
        /home/tjc/src/ruby-2.2.3/lib/rdoc/rdoc.rb:525:in `chdir'                     
        /home/tjc/src/ruby-2.2.3/lib/rdoc/rdoc.rb:525:in `generate'                  
        /home/tjc/src/ruby-2.2.3/lib/rdoc/rdoc.rb:508:in `document'                  
        ./bin/rdoc:20:in `<main>'         

uncommon.mk:427: recipe for target 'rdoc' failed                                     
make: *** [rdoc] Error 1                  
!!! Compiling ruby 2.2.3 failed! 
```

```
$ free -h     
              total        used        free      shared  buff/cache   available
Mem:            31G        5.6G         15G        1.7G         10G         23G
```

**Comment by postmodern** [comment] 2017-12-07 23:50
@TJC check your available disk space for `/home`. Also, try `watch free -h` in another terminal while RDoc is generating.

Note, that ruby-install is only responsible for downloading the source, installing dependencies, then starting the ruby's build system. Any bugs in MRI's build system should be reported upstream to https://bugs.ruby-lang.org/.

**Comment by TJC** [comment] 2017-12-07 23:58
775G of free space in /home. I was running `top` while the build ran, and didn't see memory use look troublesome -- Ruby didn't use that much really, and there was always plenty free.

Thanks for your response; I do realise this is probably a Ruby bug, but after searching this issue was the only one already existent that matched exactly. I'll take it upstream.

Cheers
