### ISSUE TITLE
Please upgrade version for brew and have a way to fetch the latest versions

### ISSUE THREAD

**Issue by timuckun** [postmodern/ruby-install#235] opened 2015-10-01 00:21 UTC
Just a feature request.

Thanks.

**Comment by havenwood** [comment] 2015-10-08 01:46
For now you can use the `brew reinstall ruby-install --HEAD` command to update to the latest master branch of ruby-install. The [cache branch](https://github.com/postmodern/ruby-install/tree/cache) supports fetching the latest versions when outdated. If you're interested in testing the cache branch any feedback is appreciated. I look forward to it in the 0.6.0 release! Closing as a duplicate of #230.

**Closed by havenwood** 2015-10-08 01:46 UTC
