### ISSUE TITLE
Ruby versions are about four months behind

### ISSUE THREAD

**Issue by MtnBiker** [postmodern/ruby-install#335] opened 2019-02-19 03:23 UTC
Is ruby-install being supported?

This is very handy to use with chruby and it would be great if it can be kept going.

**Comment by havenwood** [comment] 2019-02-19 06:43
The Ruby version metadata is maintained in the [postmodern/ruby-versions](https://github.com/postmodern/ruby-versions) repo. You can update ruby-install to the latest Ruby versions from ruby-versions with the `ruby-install --latest` command.

**Comment by havenwood** [comment] 2019-02-19 06:47
The `--latest` feature was added in #175.

**Comment by MtnBiker** [comment] 2019-02-19 17:34
On my computer:
```
ruby-install
Stable ruby versions:
  ruby:
    2.2.9
    2.3.6
    2.4.3
    2.5.0
  jruby:
    1.7.27
    9.1.15.0
  rbx:
    3.98
  maglev:
    1.0.0
  mruby:
    1.4.0
```
But Ruby is up to 2.6.1 https://www.ruby-lang.org/en/downloads/. Ruby 2.6.0 Released
 on 25 Dec 2018

**Comment by havenwood** [comment] 2019-02-20 00:30
Closing as duplicate of #275.

**Closed by havenwood** 2019-02-20 00:30 UTC
Labels: duplicate

**Comment by havenwood** [comment] 2019-02-20 00:32
Let us know if you have any issue with the latest versions with:
```sh
ruby-install --latest
```
All the latest Rubies should be there!

**Comment by MtnBiker** [comment] 2019-02-20 00:46
OP here. My bad. It would have helped if I read beyond the first command. Thanks for straightening me out. But the first command is confusing "List supported Rubies and their major versions:

$ ruby-install

I must have thought this was listing available versions, not the versions I had already installed.

**Comment by MtnBiker** [comment] 2019-02-20 04:23
@havenwood I get it now.
