### ISSUE TITLE
Support for ruby 2.6.1 ?

### ISSUE THREAD

**Issue by racer1988** [postmodern/ruby-install#336] opened 2019-03-01 11:39 UTC

**Comment by havenwood** [comment] 2019-03-01 16:53
Ruby 2.6.1 is supported! Do you not see it after running `ruby-install --latest`?

**Comment by havenwood** [comment] 2019-03-02 00:11
Closing as a duplicate of #335 and #275. We might want to consider making `ruby-install --latest` more prominent. Possibly just replacing `ruby-install` as the first example in the README.

**Closed by havenwood** 2019-03-02 00:11 UTC
Labels: duplicate

**Comment by racer1988** [comment] 2019-03-05 09:22
@havenwood Sorry for the late reply.

This is the console output of running simply `ruby-install` on macOS. I am using ruby-install coming from homebrew: 

```
 ruby-install --version
ruby-install: 0.7.0
```

``` 
ruby-install
Stable ruby versions:
  ruby:
    2.2.9
    2.3.6
    2.4.3
    2.5.0
  jruby:
    1.7.27
    9.2.0.0
  rbx:
    3.107
  truffleruby:
    1.0.0-rc6
  mruby:
    1.4.1
```

also installing Ruby 2.6.0 manually says that **the version of ruby is not supported** but will proceed anyway
